function E = eyetracker_manager(mode, P, window, E)
% =========================================================================
% eyetracker_manager  –  Unified eye tracker interface
%
%   Supports:
%     'eyelink'    – SR Research EyeLink (via Eyelink Toolbox)
%     'pupil_labs' – Pupil Labs Neon    (via pl-neon-matlab Device class)
%     'none'       – no eye tracker     (all calls silently skipped)
%
%   System is read from:  P.eyetracker.system
%
% MODES
%   E = eyetracker_manager('init',      P, window)       connect + verify
%   E = eyetracker_manager('calibrate', P, window, E)    calibrate / start recording
%       eyetracker_manager('end',       P, window, E)    stop + save + close
%
% PARAMETERS READ FROM P
%   P.eyetracker.system       'eyelink' | 'pupil_labs' | 'none'
%
%   -- EyeLink --
%   P.eyelink.calType         calibration grid, e.g. 'HV9'
%   P.edfFile                 full local filename for the renamed EDF
%   P.saveDir                 local folder to receive the EDF
%
%   -- Pupil Labs --
%   (no parameters needed for init – Device() autodiscovers the device)
%
% RETURNED E STRUCT
%   E.system        active system string (always present)
%   -- EyeLink  --  E.el, E.didCal, E.recalKey, E.continueKey
%   -- Neon     --  E.device  (live Device object)
%
% NOTES
%   - Pupil Labs requires the pl-neon-matlab package on the MATLAB path.
%   - Tested on MATLAB R2023b. Use on R2024a+ is at your own risk.
%   - Recording name is auto-generated by the Companion app (no name arg
%     supported by recording_start). Rename in Pupil Cloud post-session.
%
% Alavie / Sergio – 2025
% =========================================================================

mode = lower(strtrim(mode));

%% Guard: E required for all modes except 'init'
E_provided = (nargin >= 4) && ~isempty(E);
if ~E_provided
    if strcmp(mode, 'init')
        E = struct();
    else
        error('[eyetracker_manager] E must be provided for mode "%s".', mode);
    end
end

system = lower(strtrim(P.eyetracker.system));

% =========================================================================
switch mode

    % =====================================================================
    case 'init'
    % =====================================================================

        switch system

            % ---- EyeLink ------------------------------------------------
            case 'eyelink'
                fprintf('[EyeTracker] Initialising EyeLink...\n');

                if ~EyelinkInit()
                    error('[EyeTracker] EyelinkInit failed. Check cable / host PC.');
                end

                E.el                  = EyelinkInitDefaults(window);
                E.el.backgroundcolour = 0;
                E.el.foregroundcolour = 255;
                E.didCal              = false;
                E.recalKey            = 'r';
                E.continueKey         = 'space';
                E.system              = 'eyelink';

                % Send display geometry to tracker
                [winW, winH] = Screen('WindowSize', window);
                Eyelink('Command', 'screen_pixel_coords = 0 0 %d %d', winW-1, winH-1);
                Eyelink('Message', 'DISPLAY_COORDS 0 0 %d %d',        winW-1, winH-1);
                Eyelink('Command', 'calibration_type = %s', P.eyelink.calType);

                % Always open tracker-side file as 'tmp' (avoids 8-char limit).
                % Received as tmp.edf and renamed to P.edfFile on shutdown.
                Eyelink('OpenFile', 'tmp');
                Eyelink('Message',  'EDF_OPENED tmp');
                Eyelink('Message',  'SESSION_EYELINK_INIT_DONE');

                fprintf('[EyeTracker] EyeLink connected.  calType=%s\n', P.eyelink.calType);

            % ---- Pupil Labs ---------------------------------------------
            case 'pupil_labs'
                fprintf('[EyeTracker] Connecting to Pupil Labs Neon...\n');

                try
                    E.device = Device();
                catch ME
                    error('[EyeTracker] Could not connect to Neon device: %s', ME.message);
                end

                E.system = 'pupil_labs';
                fprintf('[EyeTracker] Pupil Labs Neon connected.\n');

            % ---- none ---------------------------------------------------
            case 'none'
                E.system = 'none';

            otherwise
                error('[eyetracker_manager] Unknown system: "%s"', system);
        end

    % =====================================================================
    case {'cal', 'calibrate', 'calibration'}
    % =====================================================================

        switch system

            % ---- EyeLink ------------------------------------------------
            case 'eyelink'
                Eyelink('Command', ...
                    'record_status_message "Press ESC to continue experiment"');
                calMsg = sprintf('Press [%s] to calibrate, or [SPACE] to skip.', ...
                    upper(E.recalKey));

                Screen('FillRect', window, 0);
                DrawFormattedText(window, calMsg, 'center', 'center', 160);
                Screen('Flip', window);

                KbName('UnifyKeyNames');
                try
                    while true
                        [down, ~, kc] = KbCheck;
                        if down
                            k = KbName(find(kc, 1));
                            if iscell(k), k = k{1}; end
                            k = lower(k);
                            if strcmp(k, E.recalKey)
                                EyelinkDoTrackerSetup(E.el);
                                E.didCal = true;
                                break;
                            elseif strcmp(k, E.continueKey)
                                break;
                            elseif strcmp(k, 'escape')
                                error('ESC_PRESSED');
                            end
                        end
                    end
                    KbReleaseWait;

                catch ME
                    if strcmp(ME.message, 'ESC_PRESSED')
                        fprintf('[EyeTracker] Aborted by user (ESC).\n');
                        emergency_close(system, E);
                        return;
                    else
                        rethrow(ME);
                    end
                end

                % Exit setup mode and start recording
                Eyelink('Command', 'set_idle_mode');
                WaitSecs(0.05);
                Eyelink('StartRecording');
                Eyelink('WaitForModeReady', 500);
                Eyelink('Message', 'EYELINK_RECORDING_STARTED');

            % ---- Pupil Labs ---------------------------------------------
            case 'pupil_labs'
                % Neon is calibration-free. Show notice, start recording,
                % then wait for experimenter keypress before task begins.
                Screen('FillRect', window, 0);
                DrawFormattedText(window, ...
                    ['Pupil Labs Neon: no calibration needed.' ...
                     '\n\nRecording is starting - press any key to continue.'], ...
                    'center', 'center', 160);
                Screen('Flip', window);

                try
                    E.device.recording_start();
                    fprintf('[EyeTracker] Neon recording started.\n');
                catch ME
                    error('[EyeTracker] Could not start Neon recording: %s', ME.message);
                end

                WaitSecs(2.0);   % allow sensors to initialise

                KbName('UnifyKeyNames');
                KbWait([], 2);
                KbReleaseWait;

            % ---- none ---------------------------------------------------
            case 'none'
                % silent no-op

        end

    % =====================================================================
    case {'end', 'off', 'shutdown', 'close'}
    % =====================================================================

        switch system

            % ---- EyeLink ------------------------------------------------
            case 'eyelink'
                Eyelink('Message', 'SESSION_END');
                Eyelink('StopRecording');
                Eyelink('CloseFile');

                % Receive tmp.edf from tracker, rename to full P.edfFile
                status = Eyelink('ReceiveFile', 'tmp', P.saveDir, 1);
                fprintf('[EyeTracker] EDF ReceiveFile status = %d\n', status);
                Eyelink('Shutdown');

                oldFile = fullfile(P.saveDir, 'tmp.edf');
                newFile = fullfile(P.saveDir, P.edfFile);
                if exist(oldFile, 'file')
                    movefile(oldFile, newFile);
                    fprintf('[EyeTracker] EDF saved as: %s\n', newFile);
                else
                    warning('[EyeTracker] EDF not found: %s', oldFile);
                end

            % ---- Pupil Labs ---------------------------------------------
            case 'pupil_labs'
                try
                    E.device.recording_stop_and_save();
                    fprintf('[EyeTracker] Neon recording stopped and saved.\n');
                catch ME
                    warning('[EyeTracker] Could not stop Neon recording: %s', ME.message);
                end

                try
                    E.device.close();
                    fprintf('[EyeTracker] Neon device closed.\n');
                catch ME
                    warning('[EyeTracker] Could not close Neon device: %s', ME.message);
                end

            % ---- none ---------------------------------------------------
            case 'none'
                % silent no-op

        end

    otherwise
        error('[eyetracker_manager] Unknown mode: "%s"', mode);

end   % switch mode

end   % main function


% =========================================================================
%  PRIVATE HELPERS
% =========================================================================

function emergency_close(system, E)
% Minimal safe shutdown called on unexpected abort (e.g. ESC during calibration).
    switch system
        case 'eyelink'
            try, Eyelink('StopRecording'); end  %#ok
            try, Eyelink('CloseFile');     end  %#ok
            try, Eyelink('Shutdown');      end  %#ok
        case 'pupil_labs'
            try, E.device.recording_stop_and_save(); end  %#ok
            try, E.device.close();                   end  %#ok
        case 'none'
    end
    try, Screen('CloseAll'); end  %#ok
end